# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25316e1a41ec93d967e99ef76be013f2cf98e9dc0c41364913b9d518941871a5d475abff1a3364dce69d056726222b1bdd0693fdad12299685669fd37906728

test:
  secret_key_base: 11dcaa1074498e7689d67f315f6ab34a622a21abab8e69e4fed0cd06d1ff2f358af0ddf044360862b524a73a3f832eaf4b722f42bb6a034229b6d5df8814f569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
